#!/usr/bin/env bash

readonly arch="\033[38;2;23;147;209m"
readonly red="\033[31m"
readonly nc="\033[0m"

if [ $# -lt 1 ]; then
    MSG="Usage: ./box_text <text>"
else
    MSG="$1"
fi

length=$((${#MSG}+8))

draw_horizontal() {
    echo -ne "\033[38;2;23;147;209m+"
    for i in $(seq 1 $length);do
        echo -ne "="
    done
    echo -e "+\033[0m"
}

draw_horizontal
echo -ne "${red}|    ${arch}$MSG    ${red}|${nc}\n"
draw_horizontal
echo ""
# \033[38;2;23;147;209m+=========================================================================================+
# |                                                                                         |
# |                                                                                         |
# |                                                                                         |
# |                                                                                         |
# |                                                                                         |
# |                                                                                         |
# |                                                                                         |
# |                                                                                         |
# |                                                                                         |
# |                                                                                         |
# |                                                                                         |
# |                                                                                         |
# |                                                                                         |
# |                                                                                         |
# |                                                                                         |
# |                                                                                         |
